version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - NGINX_REPOSITORY_URI01=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_IMAGE_REPO_NAME01
      - NGINX_REPOSITORY_URI02=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_IMAGE_REPO_NAME02    
      - IMAGE_TAG=1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for nginx01...
      - docker build -t $NGINX_REPOSITORY_URI01:$IMAGE_TAG nginx01/
      - echo Building the Docker image for nginx02...
      - docker build -t $NGINX_REPOSITORY_URI02:$IMAGE_TAG nginx02/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image for nginx01...
      - docker push $NGINX_REPOSITORY_URI01:$IMAGE_TAG
      - IMAGE_URL1=$NGINX_REPOSITORY_URI01:$IMAGE_TAG
      - echo Pushing the Docker image for nginx02...
      - docker push $NGINX_REPOSITORY_URI02:$IMAGE_TAG
      - IMAGE_URL2=$NGINX_REPOSITORY_URI02:$IMAGE_TAG
      - sed -i -e "s#<TASK_FAMILY01>#${TASK_FAMILY01}#" stg01/nginx01-taskdef.json
      - sed -i -e "s#<TASK_FAMILY02>#${TASK_FAMILY02}#" stg01/nginx02-taskdef.json
      - sed -i -e "s#<EXECUTION_ROLE_ARN>#${EXECUTION_ROLE_ARN}#" stg01/nginx01-taskdef.json
      - sed -i -e "s#<EXECUTION_ROLE_ARN>#${EXECUTION_ROLE_ARN}#" stg01/nginx02-taskdef.json
      - sed -i -e "s#<CONTAINER_NAME01>#${CONTAINER_NAME01}#" stg01/nginx01-taskdef.json
      - sed -i -e "s#<CONTAINER_NAME02>#${CONTAINER_NAME02}#" stg01/nginx02-taskdef.json
      - sed -i -e "s#<IMAGE1_NAME>#${IMAGE_URL1}#" stg01/nginx01-taskdef.json
      - sed -i -e "s#<IMAGE2_NAME>#${IMAGE_URL2}#" stg01/nginx02-taskdef.json
      - sed -i -e "s#<CONTAINER_NAME01>#${CONTAINER_NAME01}#" nginx01-appspec.yaml
      - sed -i -e "s#<CONTAINER_NAME02>#${CONTAINER_NAME02}#" nginx02-appspec.yaml
artifacts:
  files:
    - stg01/nginx01-taskdef.json
    - stg01/nginx02-taskdef.json
    - nginx01-appspec.yaml
    - nginx02-appspec.yaml