version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "<CONTAINER_NAME01>"
          ContainerPort: 80
        CapacityProviderStrategy:
          - Base: 0
            CapacityProvider: "test-capacityprovider-az1a"
            Weight: 1
          - Base: 0
            CapacityProvider: "test-capacityprovider-az1c"
            Weight: 1